-- =========================================================================
-- Script SQL para módulo de Reparaciones
-- Ejecutar en Supabase -> SQL Editor -> New Query
-- =========================================================================

-- 1. Crear la tabla principal
CREATE TABLE public.reparaciones (
    id bigint generated by default as identity primary key,
    nro_orden text,
    fecha_ingreso timestamp with time zone default timezone('utc'::text, now()) not null,
    cliente text not null,
    telefono text,
    equipo text,
    codigo_desbloqueo text,
    fallas text,
    presupuesto numeric default 0,
    estado text default 'Ingresado',
    historial_pagos jsonb default '[]'::jsonb
);

-- 2. Habilitar seguridad por fila (RLS)
ALTER TABLE public.reparaciones ENABLE ROW LEVEL SECURITY;

-- 3. Crear política para que solo usuarios logueados (empleados/dueños) puedan acceder y modificar
CREATE POLICY "Acceso total a reparaciones para usuarios autenticados"
ON public.reparaciones
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

-- 4. Insertar 10 registros de prueba (Mock Data)
INSERT INTO public.reparaciones 
(nro_orden, fecha_ingreso, cliente, telefono, equipo, codigo_desbloqueo, fallas, presupuesto, estado, historial_pagos)
VALUES
('A-1001', now() - interval '5 days', 'Carlos Gómez', '3415551234', 'Samsung S20 FE', 'Patrón Z', 'No carga, pin roto. Cambiar módulo de carga.', 25000, 'Reparado', '[{"fecha": "2026-06-12T10:00:00.000Z", "monto": 10000, "metodo": "efectivo"}]'::jsonb),

('A-1002', now() - interval '4 days', 'María Silva', '3415559876', 'iPhone 11', '123456', 'Pantalla astillada. El táctil funciona a medias.', 65000, 'Esperando repuesto', '[]'::jsonb),

('A-1003', now() - interval '4 days', 'Juan Pérez', '3415554321', 'Motorola G30', 'Sin clave', 'Se mojó. No prende ni da luz de carga.', 45000, 'En revisión', '[{"fecha": "2026-06-13T15:30:00.000Z", "monto": 5000, "metodo": "transferencia"}]'::jsonb),

('A-1004', now() - interval '3 days', 'Lucía Rossi', '3415551111', 'Xiaomi Redmi Note 10', '4321', 'Cámara trasera borrosa.', 18000, 'Ingresado', '[]'::jsonb),

('A-1005', now() - interval '2 days', 'Marcos López', '3415552222', 'iPhone 13 Pro', '2580', 'Batería dura 2 horas. Reemplazo de batería.', 50000, 'Entregado', '[{"fecha": "2026-06-15T09:00:00.000Z", "monto": 25000, "metodo": "efectivo"}, {"fecha": "2026-06-16T17:00:00.000Z", "monto": 25000, "metodo": "debito"}]'::jsonb),

('A-1006', now() - interval '2 days', 'Valeria Martínez', '3415553333', 'Samsung A52', 'Patrón L', 'No lee chip (SIM no detectada).', 22000, 'Reparado', '[]'::jsonb),

('A-1007', now() - interval '1 days', 'Esteban Castro', '3415554444', 'Motorola Edge 30', '0000', 'Vidrio templado e instalación.', 8000, 'Entregado', '[{"fecha": "2026-06-16T10:00:00.000Z", "monto": 8000, "metodo": "transferencia"}]'::jsonb),

('A-1008', now() - interval '1 days', 'Sofía Giménez', '3415556666', 'iPhone 8 Plus', '112233', 'Botón home no funciona.', 15000, 'En revisión', '[]'::jsonb),

('A-1009', now(), 'Daniel Ríos', '3415557777', 'Xiaomi POCO X3', 'Patrón cruz', 'Se apaga solo al exigir juegos.', 35000, 'Ingresado', '[{"fecha": "2026-06-17T11:00:00.000Z", "monto": 10000, "metodo": "efectivo"}]'::jsonb),

('A-1010', now(), 'Analía Costa', '3415558888', 'Samsung S22 Ultra', 'Sin clave', 'Tapa trasera fisurada. Presupuestar.', 40000, 'Esperando repuesto', '[]'::jsonb);
